# Generated by Django 3.2.20 on 2023-08-17 15:01

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230817_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to=core.models.recipe_image_file_path, validators=[django.core.validators.FileExtensionValidator(['png'])]),
        ),
    ]
